name = "g7petsgrooming-api"
main = "src/index.ts"
compatibility_date = "2026-02-17"
workers_dev = true

[vars]
APP_ENV = "prod"
PUBLIC_UI_ORIGIN = "https://g7petsgrooming-public.pages.dev"
ADMIN_UI_ORIGIN = "https://g7petsgrooming-admin.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "g7petsgrooming-db"
database_id = "086a7638-253d-4f1d-a979-0592dabb9acd"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "GALLERY_BUCKET"
bucket_name = "g7petsgrooming-gallery"
preview_bucket_name = "g7petsgrooming-gallery-preview"
